// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
//
// For more information, please visit:
// https://firebase.google.com/docs/build
export const firebaseConfig = {
  "apiKey": "AIzaSyBvM114YUPohSdll5X7qRuGzgYPl9giXL4",
  "authDomain": "studio-1828396560-1b149.firebaseapp.com",
  "projectId": "studio-1828396560-1b149",
  "storageBucket": "studio-1828396560-1b149.appspot.com",
  "messagingSenderId": "262702036163",
  "appId": "1:262702036163:web:6d862d5d6d0a7714725e76"
};
